### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by jl5000** [dapperstats/gendrendr#14]
There seems to be some terms in the readme which have either been redefined, or are a bit confusing:

1. Acts of "violence" are usually confined to those of physical force - if redefining terms like this, it may be worth clarifying why

2. What does "fancy statistics" mean? Invalid/flawed/irrelevant statistics? Statistics that are needlessly complex?

**Comment by juniperlsimonis** [comment]
1. violence is not restricted to physical acts. this is not a redefinition. 
2. it's intentionally vague. it's a critique, so calling something fancy is an intentional undercut.
